version: "3.8"
services:
  mongodb_pokedex:
    container_name: pokedex-api-mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
    - mongodb_pokedex_container:/data/db
  redis_pokedex:
    image: redis:latest
    ports: 
      - 6379:6379
volumes:
  mongodb_pokedex_container:
