version: "3.8"
services:
  api:
    container_name: pokedex-api
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb_pokedex
    environment:
      HOST_PORT: 8080
      MONGODB_ADDRS: localhost:27018
      MONGODB_NAME: pokedex-db
  mongodb_pokedex:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
    - mongodb_pokedex_container:/data/db
volumes:
  mongodb_pokedex_container:
