// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"

	presenter "github.com/ricardoham/pokedex-api/api/presenter"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: e
func (_m *Repository) Create(e *presenter.Pokemon) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*presenter.Pokemon) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, pokeID
func (_m *Repository) Delete(ctx context.Context, pokeID presenter.DeletePokemon) (*mongo.DeleteResult, error) {
	ret := _m.Called(ctx, pokeID)

	var r0 *mongo.DeleteResult
	if rf, ok := ret.Get(0).(func(context.Context, presenter.DeletePokemon) *mongo.DeleteResult); ok {
		r0 = rf(ctx, pokeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, presenter.DeletePokemon) error); ok {
		r1 = rf(ctx, pokeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, pokemons
func (_m *Repository) FindAll(ctx context.Context, pokemons []*presenter.Pokemon) ([]*presenter.Pokemon, error) {
	ret := _m.Called(ctx, pokemons)

	var r0 []*presenter.Pokemon
	if rf, ok := ret.Get(0).(func(context.Context, []*presenter.Pokemon) []*presenter.Pokemon); ok {
		r0 = rf(ctx, pokemons)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*presenter.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []*presenter.Pokemon) error); ok {
		r1 = rf(ctx, pokemons)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOne provides a mock function with given fields: ctx, pokeID, _a2
func (_m *Repository) FindOne(ctx context.Context, pokeID string, _a2 *presenter.Pokemon) error {
	ret := _m.Called(ctx, pokeID, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *presenter.Pokemon) error); ok {
		r0 = rf(ctx, pokeID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, pokeID, updateData
func (_m *Repository) Update(ctx context.Context, pokeID string, updateData *presenter.UpdatePokemon) (*mongo.UpdateResult, error) {
	ret := _m.Called(ctx, pokeID, updateData)

	var r0 *mongo.UpdateResult
	if rf, ok := ret.Get(0).(func(context.Context, string, *presenter.UpdatePokemon) *mongo.UpdateResult); ok {
		r0 = rf(ctx, pokeID, updateData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *presenter.UpdatePokemon) error); ok {
		r1 = rf(ctx, pokeID, updateData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
